version: 2
jobs:
  build:
    machine: true
    working_directory: ~/gliderlabs/herokuish
    parallelism: 4
    steps:
      - checkout
      - run: |
          make circleci
      - run: |
          make deps
      - run: |
          make shellcheck
      - run: |
          make build
      - run: |
          make lint
      - run: |
          ls -la /.circleci-task-data/circle-test-results/
      - run: |
          case $CIRCLE_NODE_INDEX in 0) basht tests/**/tests.sh ;; esac
      - run: |
          circleci tests glob buildpacks/*/tests/*/test.sh | circleci tests split --split-by=timings --timings-type=filename
      - run: |
          basht $(circleci tests glob buildpacks/*/tests/*/test.sh | circleci tests split --split-by=timings --timings-type=filename)
      - run: |
          ls -la /.circleci-task-data/circle-test-results/
      - deploy:
          name: release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              make release
            fi
