version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: ~/gliderlabs/herokuish
    parallelism: 4
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.1-ce
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make deb-setup shellcheck;; esac
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make lint;; esac
      - run: |
          make circleci
      - run: |
          make deps
      - run: |
          cd ~/gliderlabs/herokuish
          docker create -v /${PWD} --name buildpacks alpine:3.4 /bin/true
          docker cp --follow-link "$PWD/buildpacks" buildpacks:/${PWD}/buildpacks
      - run: |
          make build
      - run: |
          case $CIRCLE_NODE_INDEX in 0) basht tests/**/tests.sh ;; esac
      - run: |
          circleci tests glob buildpacks/*/tests/*/test.sh | circleci tests split --split-by=timings --timings-type=classname
          basht $(circleci tests glob buildpacks/*/tests/*/test.sh | circleci tests split --split-by=timings --timings-type=classname)
      - deploy:
          name: release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              make release
            fi
